CREATE TABLE device (
    Id UUID PRIMARY KEY DEFAULT,
    name VARCHAR(50) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    state VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)