server:
  port: 8000
  servlet:
    context-path: /device-service

spring:
  application:
    name: Device Service

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}